#server:
#  port: 8082
#
#spring:
#  profiles:
#    active: qa
#---
#
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: admin
#    url: jdbc:mysql://localhost:3306/dcbapp
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Welcome to spring boot
#
#---
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: admin
#    url: jdbc:mysql://localhost:3306/dcbapp-qa
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Welcome to spring boot
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: admin
#    url: jdbc:mysql://localhost:3306/dcbapp-prod
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Welcome to spring boot